In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shlokbagwe/main-classification-df-v2/classification_df_v2.parquet
/kaggle/input/datasets/shlokbagwe/classification-train-test-df/test_df.parquet
/kaggle/input/datasets/shlokbagwe/classification-train-test-df/train_df.parquet
/kaggle/input/datasets/shlokbagwe/classification-df/df_classification_2.parquet

In [2]:
train_df = pd.read_parquet('/kaggle/input/datasets/shlokbagwe/classification-train-test-df/train_df.parquet')
test_df = pd.read_parquet('/kaggle/input/datasets/shlokbagwe/classification-train-test-df/test_df.parquet')

In [3]:
train_df.head()

,amount,use_chip,errors,abs_amount,target_numeric,gender,num_credit_cards,card_brand,card_type,has_chip,...,amount_zscore,mcc_fraud_rate,mcc_avg_amount,mcc_txn_count,city_fraud_rate,city_avg_amount,city_unique_customers,state_txn_count,client_fraud_rate,is_online
0,-77.00,Swipe Transaction,No Error,77.00,0.0,1,4,Mastercard,Debit (Prepaid),1,...,0.101336,0.000002,41.348915,807904,0.000000,68.709122,13,12388,0.003477,0
1,80.00,Swipe Transaction,No Error,80.00,0.0,0,3,Mastercard,Debit,1,...,0.459925,0.002286,90.184654,317560,0.000000,68.977081,40,773095,0.000629,0
2,14.57,Swipe Transaction,No Error,14.57,0.0,0,5,Mastercard,Credit,1,...,-0.380896,0.006168,56.963947,255855,0.000000,59.643684,16,86235,0.005267,0
3,46.41,Swipe Transaction,No Error,46.41,0.0,0,2,Visa,Debit,1,...,-0.413219,0.000599,25.170216,133609,0.001356,66.795120,5,104472,0.001960,0
4,4.81,Swipe Transaction,No Error,4.81,0.0,1,5,Mastercard,Debit (Prepaid),1,...,-0.599840,0.000353,19.289579,124678,0.000000,47.624516,169,464253,0.000749,0

In [4]:
test_df.head()

,amount,use_chip,errors,abs_amount,target_numeric,gender,num_credit_cards,card_brand,card_type,has_chip,...,amount_zscore,mcc_fraud_rate,mcc_avg_amount,mcc_txn_count,city_fraud_rate,city_avg_amount,city_unique_customers,state_txn_count,client_fraud_rate,is_online
0,39.130001,Chip Transaction,No Error,39.130001,0.0,1,6,Visa,Debit,1,...,-0.311900,0.000145,42.635479,27607,0.000133,52.629848,35.0,125174.0,0.002650,0
1,84.000000,Chip Transaction,No Error,84.000000,0.0,1,5,Mastercard,Debit,1,...,0.611699,0.000002,41.348915,807904,0.000131,42.097229,6.0,773095.0,0.001135,0
2,48.070000,Chip Transaction,No Error,48.070000,0.0,1,6,Visa,Credit,1,...,-0.040758,0.000017,46.795773,57329,0.000421,44.867401,215.0,90859.0,0.002491,0
3,117.879997,Chip Transaction,No Error,117.879997,0.0,1,5,Mastercard,Debit,1,...,1.365174,0.000570,157.015060,17548,0.000000,49.511288,74.0,381782.0,0.001917,0
4,12.820000,Chip Transaction,No Error,12.820000,0.0,0,3,Mastercard,Debit (Prepaid),1,...,-0.405051,0.000014,51.667759,790222,0.000000,40.472355,58.0,773095.0,0.001636,0

In [5]:
df = pd.read_parquet('/kaggle/input/datasets/shlokbagwe/main-classification-df-v2/classification_df_v2.parquet')
df.head()

,date,time,client_id_x,amount,use_chip,merchant_city,merchant_state,mcc,errors,abs_amount,...,available_credit_per_card,hour,day_of_week,weekend_flag,account_age_years,years_since_pin_change,credit_limit_to_income,transaction_datetime,txn_count_last_24h,amount_sum_last_24h
0,2010-01-01,00:01:00,1556,-77.00,Swipe Transaction,Beulah,ND,5499,None,77.00,...,13.75,0,4,0,2,2,0.001139,2010-01-01 00:01:00,0,0.0
1,2010-01-01,00:02:00,1129,80.00,Swipe Transaction,Vista,CA,4829,None,80.00,...,4934.00,0,4,0,4,2,0.429679,2010-01-01 00:02:00,0,0.0
2,2010-01-01,00:02:00,561,14.57,Swipe Transaction,Bettendorf,IA,5311,None,14.57,...,1820.00,0,4,0,5,-5,0.246927,2010-01-01 00:02:00,0,0.0
3,2010-01-01,00:06:00,848,46.41,Swipe Transaction,Harwood,MD,5813,None,46.41,...,9556.50,0,4,0,1,-4,0.279585,2010-01-01 00:06:00,0,0.0
4,2010-01-01,00:07:00,1807,4.81,Swipe Transaction,Bronx,NY,5942,None,4.81,...,17.80,0,4,0,2,-5,0.001709,2010-01-01 00:07:00,0,0.0

In [6]:
df = df.sort_values(by=['transaction_datetime']).reset_index(drop=True)

In [7]:
df.shape

(8993227, 34)

In [8]:
split_point = int(len(df) * 0.8)
split_date = df.iloc[split_point]['transaction_datetime']

train_2 = df[df['transaction_datetime'] < split_date].copy()
test_2 = df[df['transaction_datetime'] >= split_date].copy()

In [9]:
train_df_cols = train_df.columns

In [10]:
set(train_2.columns) - set(train_df_cols)

{'available_credit_per_card',
 'client_id_x',
 'credit_limit',
 'credit_limit_to_income',
 'credit_score',
 'current_age',
 'date',
 'mcc',
 'merchant_city',
 'merchant_state',
 'per_capita_income',
 'time',
 'total_debt',
 'transaction_datetime',
 'yearly_income'}

In [11]:
train_df.shape

(7194581, 31)

In [12]:
train_2.shape

(7194581, 34)

In [13]:
(train_df.index.equals(train_2.index))

True

In [14]:
cols = ['client_id_x', 'current_age', 'mcc', 'merchant_city','merchant_state', 'transaction_datetime', 'date', 'time']
train_df = pd.concat(
    [train_df, train_2[cols]],
    axis=1
)
test_df = pd.concat([test_df, test_2[cols]], axis=1)

In [15]:
train_2.groupby('mcc')['target_numeric'].mean().sort_values(ascending=False)

mcc
4411    0.644269
5733    0.351852
3006    0.114428
5732    0.106322
3144    0.096591
          ...
6300    0.000000
7276    0.000000
7393    0.000000
8111    0.000000
8931    0.000000
Name: target_numeric, Length: 109, dtype: float64

In [16]:
train_df.drop(columns = ['gender', 'card_brand', 'has_chip', 'debt_to_income', 'num_cards_issued'], inplace=True, axis=1)

In [17]:
test_df.drop(columns = ['gender', 'card_brand', 'has_chip', 'debt_to_income', 'num_cards_issued'], inplace=True, axis=1)

In [18]:
train_df.columns

Index(['amount', 'use_chip', 'errors', 'abs_amount', 'target_numeric',
       'num_credit_cards', 'card_type', 'hour', 'day_of_week', 'weekend_flag',
       'account_age_years', 'years_since_pin_change', 'txn_count_last_24h',
       'amount_sum_last_24h', 'customer_avg_amount', 'customer_txn_count',
       'amount_zscore', 'mcc_fraud_rate', 'mcc_avg_amount', 'mcc_txn_count',
       'city_fraud_rate', 'city_avg_amount', 'city_unique_customers',
       'state_txn_count', 'client_fraud_rate', 'is_online', 'client_id_x',
       'current_age', 'mcc', 'merchant_city', 'merchant_state',
       'transaction_datetime', 'date', 'time'],
      dtype='object')

In [19]:
train_df['mcc'].value_counts()

mcc
5411    855355
5499    807904
5541    790222
5812    536614
5912    415688
         ...
3006       201
3075       197
5722       191
3144       176
5733       162
Name: count, Length: 109, dtype: int64

In [20]:
train_df['merch_total_txns'] = train_df.groupby('mcc').cumcount()
test_df['merch_total_txns'] = test_df.groupby('mcc').cumcount()

In [21]:
train_df['prev_mcc_txns'] = train_df.groupby('mcc').cumcount()

temp = train_df.groupby('mcc')['target_numeric'].cumsum()

train_df['prev_mcc_frauds'] = temp.groupby(train_df['mcc']).shift(1).fillna(0)

train_df['previous_mcc_risk_score'] = (
    train_df['prev_mcc_frauds'] / train_df['prev_mcc_txns']
)


train_df['previous_mcc_risk_score'] = (
    train_df['previous_mcc_risk_score']
      .replace([np.inf, -np.inf], 0)
      .fillna(0)
)

In [22]:
# Creating previous mcc risk score for diff types of mccs

test_df['prev_mcc_txns'] = test_df.groupby('mcc').cumcount()

temp = test_df.groupby('mcc')['target_numeric'].cumsum()

test_df['prev_mcc_frauds'] = temp.groupby(test_df['mcc']).shift(1).fillna(0)

test_df['previous_mcc_risk_score'] = (
    test_df['prev_mcc_frauds'] / test_df['prev_mcc_txns']
)

test_df['previous_mcc_risk_score'] = (
    test_df['previous_mcc_risk_score']
      .replace([np.inf, -np.inf], 0)
      .fillna(0)
)

In [23]:
train_df.sample(5)

,amount,use_chip,errors,abs_amount,target_numeric,num_credit_cards,card_type,hour,day_of_week,weekend_flag,...,mcc,merchant_city,merchant_state,transaction_datetime,date,time,merch_total_txns,prev_mcc_txns,prev_mcc_frauds,previous_mcc_risk_score
2056941,162.190002,Swipe Transaction,No Error,162.190002,0.0,2,Debit,15,2,0,...,4900,Memphis,TN,2012-05-23 15:28:00,2012-05-23,15:28:00,37429,37429,9.0,0.000240
442398,31.110001,Online Transaction,No Error,31.110001,0.0,6,Credit,9,3,0,...,5812,Midlothian,VA,2010-07-15 09:41:00,2010-07-15,09:41:00,32645,32645,30.0,0.000919
3193919,27.490000,Swipe Transaction,Insufficient Balance,27.490000,0.0,3,Debit,7,6,1,...,5411,Elma,NY,2013-08-25 07:38:00,2013-08-25,07:38:00,380466,380466,180.0,0.000473
2100573,0.650000,Swipe Transaction,No Error,0.650000,0.0,2,Credit,11,6,1,...,5411,Fort Lauderdale,FL,2012-06-10 11:46:00,2012-06-10,11:46:00,249903,249903,143.0,0.000572
1555088,91.360001,Swipe Transaction,No Error,91.360001,0.0,2,Debit,15,4,0,...,5300,Saint Louis,MO,2011-10-28 15:35:00,2011-10-28,15:35:00,70781,70781,178.0,0.002515

In [24]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7194581 entries, 0 to 7194580
Data columns (total 38 columns):
 #   Column                   Dtype
---  ------                   -----
 0   amount                   float32
 1   use_chip                 object
 2   errors                   object
 3   abs_amount               float32
 4   target_numeric           float64
 5   num_credit_cards         int8
 6   card_type                object
 7   hour                     int32
 8   day_of_week              int32
 9   weekend_flag             int64
 10  account_age_years        int32
 11  years_since_pin_change   int64
 12  txn_count_last_24h       uint32
 13  amount_sum_last_24h      float32
 14  customer_avg_amount      float32
 15  customer_txn_count       int64
 16  amount_zscore            float32
 17  mcc_fraud_rate           float64
 18  mcc_avg_amount           float32
 19  mcc_txn_count            int64
 20  city_fraud_rate          float64
 21  city_avg_amount          float32
 22  city_unique_customers    int64
 23  state_txn_count          int64
 24  client_fraud_rate        float64
 25  is_online                int8
 26  client_id_x              int16
 27  current_age              int8
 28  mcc                      int16
 29  merchant_city            object
 30  merchant_state           object
 31  transaction_datetime     datetime64[ns]
 32  date                     datetime64[ns]
 33  time                     object
 34  merch_total_txns         int64
 35  prev_mcc_txns            int64
 36  prev_mcc_frauds          float64
 37  previous_mcc_risk_score  float64
dtypes: datetime64[ns](2), float32(7), float64(6), int16(2), int32(3), int64(8), int8(3), object(6), uint32(1)
memory usage: 1.5+ GB

In [25]:
train_df.drop(columns = ['prev_mcc_txns', 'prev_mcc_frauds'], inplace=True)
test_df.drop(columns = ['prev_mcc_txns', 'prev_mcc_frauds'], inplace=True)

In [26]:
top_10_states = train_df['merchant_state'].value_counts().head(10)

In [27]:
train_df['merchant_state'] = train_df['merchant_state'].apply(lambda x: x if x in top_10_states or x == "online" else "Other_State")

In [28]:
top_10_cities = (
    train_df.groupby('merchant_city').agg(
          total_transactions=('target_numeric', 'size'),
          fraud_transactions=('target_numeric', 'sum'),
          fraud_rate=('target_numeric', 'mean')
      )
      .sort_values('total_transactions', ascending=False)
      .head(10)
      .reset_index()
)

top_10_cities['fraud_rate'] *= 100 
top_10_cities

  merchant_city  total_transactions  fraud_transactions  fraud_rate
0        Online              833580              6482.0    0.777610
1       Houston               80422                36.0    0.044764
2         Miami               47885                28.0    0.058473
3      Brooklyn               45282                15.0    0.033126
4   Los Angeles               44722                26.0    0.058137
5       Chicago               39377                20.0    0.050791
6        Dallas               39063                20.0    0.051199
7    Louisville               35574                18.0    0.050599
8  Philadelphia               33494                14.0    0.041799
9   San Antonio               31861                 9.0    0.028248

In [29]:
top_10_states = (
    train_df.groupby('merchant_state').agg(
          total_transactions=('target_numeric', 'size'),
          fraud_transactions=('target_numeric', 'sum'),
          fraud_rate=('target_numeric', 'mean')
      )
      .sort_values('total_transactions', ascending=False).head(10)
      .reset_index()
)

top_10_states['fraud_rate'] *= 100 
top_10_states

  merchant_state  total_transactions  fraud_transactions  fraud_rate
0    Other_State             3635913              8239.0    0.226601
1             CA              773095               424.0    0.054844
2             TX              548475               278.0    0.050686
3             NY              464253               236.0    0.050834
4             FL              381782               241.0    0.063125
5             OH              262514               323.0    0.123041
6             IL              254710               159.0    0.062424
7             NC              233258               145.0    0.062163
8             PA              226010               112.0    0.049555
9             MI              215094               118.0    0.054860